[[stack]]
name = "prowlarr"

[stack.config]
server = "Local"
repo = "xkicken/komodo-compose"
branch = "main"
file_paths = ["compose-file/prowlarr/compose.yaml"]

[[stack]]
name = "sonarr"

[stack.config]
server = "Local"
repo = "xkicken/komodo-compose"
branch = "main"
compose_file_path = "compose-file/sonarr/compose.yaml"