[[stack]]
name = "prowlarr"

[stack.config]
server = "Local"
git_provider = "github.com"
git_account = "xkicken"
repo = "xkicken/komodo-compose"
branch = "main"
file_paths = ["compose-file/prowlarr/compose.yaml"]

[[stack]]
name = "sonarr"

[stack.config]
server = "Local"
git_provider = "github.com"
git_account = "xkicken"
repo = "xkicken/komodo-compose"
branch = "main"
file_paths = ["compose-file/sonarr/compose.yaml"]